In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("student_data.csv")

In [3]:
df.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [4]:
df['higher'] = df['higher'].map({
    'yes': 1,
    'no': 0
})

In [5]:
numerical_features = [
    'age',
    'Medu',
    'Fedu',
    'traveltime',
    'studytime',
    'failures',
    'famrel',
    'freetime',
    'goout',
    'Dalc',
    'Walc',
    'health',
    'absences',
    'G1',
    'G2'
]

In [6]:
X = df[numerical_features]
y = df['higher']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
scaler = StandardScaler()

In [9]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
k_values = [3, 5, 7]

In [11]:
results = []

In [12]:
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    y_pred = knn.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    results.append({
        'k': k,
        'Accuracy': accuracy
    })

In [13]:
results_df = pd.DataFrame(results)

In [14]:
results_df

   k  Accuracy
0  3  0.987342
1  5  0.987342
2  7  0.974684

In [15]:
best_row = results_df.loc[
    results_df['Accuracy'].idxmax()
]

In [16]:
best_k = int(best_row['k'])
best_accuracy = best_row['Accuracy']

In [17]:
best_k

3

In [18]:
best_accuracy

np.float64(0.9873417721518988)

In [20]:
k_values = [3, 5, 7]
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    y_pred = knn.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    print("\nk =", k)
    print("Accuracy =", accuracy)
    print("First 10 Predictions:", y_pred[:10])

k = 3
Accuracy = 0.9873417721518988
First 10 Predictions: [0 1 1 1 1 1 1 1 1 1]

k = 5
Accuracy = 0.9873417721518988
First 10 Predictions: [0 1 1 1 1 1 1 1 1 1]

k = 7
Accuracy = 0.9746835443037974
First 10 Predictions: [1 1 1 1 1 1 1 1 1 1]