In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Walmart_Sales.csv")
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [4]:
df.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='str')

In [5]:
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")

In [6]:
df["Date"].head()

0   2010-02-05
1   2010-02-12
2   2010-02-19
3   2010-02-26
4   2010-03-05
Name: Date, dtype: datetime64[us]

In [7]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

In [8]:
df[["Date", "Year", "Month", "Day"]].head()

        Date  Year  Month  Day
0 2010-02-05  2010      2    5
1 2010-02-12  2010      2   12
2 2010-02-19  2010      2   19
3 2010-02-26  2010      2   26
4 2010-03-05  2010      3    5

In [9]:
text_columns = df.select_dtypes(include="object").columns

In [10]:
text_columns.tolist()

[]

In [11]:
dfs = pd.read_csv("student_data.csv")

In [14]:
text_columns_stu = dfs.select_dtypes(include="object").columns

C:\Users\verve\AppData\Local\Temp\ipykernel_4576\3063449899.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns_stu = dfs.select_dtypes(include="object").columns

In [15]:
text_columns_stu.tolist()

['school',
 'sex',
 'address',
 'famsize',
 'Pstatus',
 'Mjob',
 'Fjob',
 'reason',
 'guardian',
 'schoolsup',
 'famsup',
 'paid',
 'activities',
 'nursery',
 'higher',
 'internet',
 'romantic']

In [22]:
dfs["reason_length"] = dfs["reason"].str.len()

In [23]:
dfs[["reason", "reason_length"]].head()

   reason  reason_length
0  course              6
1  course              6
2   other              5
3    home              4
4    home              4

In [24]:
dfs["reason_word_count"] = dfs["reason"].str.split().str.len()
dfs[["reason", "reason_length", "reason_word_count"]].head()

   reason  reason_length  reason_word_count
0  course              6                  1
1  course              6                  1
2   other              5                  1
3    home              4                  1
4    home              4                  1