In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("student_data.csv")
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [4]:
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
numerical_cols

['age',
 'Medu',
 'Fedu',
 'traveltime',
 'studytime',
 'failures',
 'famrel',
 'freetime',
 'goout',
 'Dalc',
 'Walc',
 'health',
 'absences',
 'G1',
 'G2',
 'G3']

In [5]:
scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [6]:
df_scaled.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,1.023046,U,GT3,A,1.143856,1.360371,at_home,teacher,...,0.062194,-0.236010,0.801479,-0.540699,-1.003789,-0.399289,0.036424,-1.782467,-1.254791,-0.964934
1,GP,F,0.238380,U,GT3,T,-1.600009,-1.399970,at_home,other,...,1.178860,-0.236010,-0.097908,-0.540699,-1.003789,-0.399289,-0.213796,-1.782467,-1.520979,-0.964934
2,GP,F,-1.330954,U,LE3,T,-1.600009,-1.399970,at_home,other,...,0.062194,-0.236010,-0.997295,0.583385,0.551100,-0.399289,0.536865,-1.179147,-0.722415,-0.090739
3,GP,F,-1.330954,U,GT3,T,1.143856,-0.479857,health,services,...,-1.054472,-1.238419,-0.997295,-0.540699,-1.003789,1.041070,-0.464016,1.234133,0.874715,1.002004
4,GP,F,-0.546287,U,GT3,T,0.229234,0.440257,other,other,...,0.062194,-0.236010,-0.997295,-0.540699,-0.226345,1.041070,-0.213796,-1.480807,-0.190038,-0.090739

In [7]:
df_scaled[numerical_cols].mean()

age           1.223213e-15
Medu          5.396527e-17
Fedu         -1.439074e-16
traveltime    6.295948e-17
studytime    -2.113640e-16
failures     -1.349132e-17
famrel       -1.394103e-16
freetime      1.079305e-16
goout        -1.214219e-16
Dalc          1.349132e-16
Walc         -1.798842e-16
health        7.195369e-17
absences     -5.396527e-17
G1            8.994212e-17
G2           -4.946817e-17
G3           -9.443922e-17
dtype: float64

In [8]:
df_scaled[numerical_cols].std()

age           1.001268
Medu          1.001268
Fedu          1.001268
traveltime    1.001268
studytime     1.001268
failures      1.001268
famrel        1.001268
freetime      1.001268
goout         1.001268
Dalc          1.001268
Walc          1.001268
health        1.001268
absences      1.001268
G1            1.001268
G2            1.001268
G3            1.001268
dtype: float64

In [9]:
df_scaled[numerical_cols].std(ddof=0)

age           1.0
Medu          1.0
Fedu          1.0
traveltime    1.0
studytime     1.0
failures      1.0
famrel        1.0
freetime      1.0
goout         1.0
Dalc          1.0
Walc          1.0
health        1.0
absences      1.0
G1            1.0
G2            1.0
G3            1.0
dtype: float64