In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("student_data.csv")
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [3]:
df['higher'] = df['higher'].map({
    'yes': 1,
    'no': 0
})

In [4]:
numerical_features = [
    'age',
    'Medu',
    'Fedu',
    'traveltime',
    'studytime',
    'failures',
    'famrel',
    'freetime',
    'goout',
    'Dalc',
    'Walc',
    'health',
    'absences',
    'G1',
    'G2'
]

In [5]:
X = df[numerical_features]
y = df['higher']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train, y_train)
logistic_pred = logistic_model.predict(X_test)
logistic_accuracy = accuracy_score(
    y_test,
    logistic_pred
)

In [8]:
nb_model = GaussianNB()

In [9]:
nb_model.fit(X_train, y_train)
nb_pred = nb_model.predict(X_test)
nb_accuracy = accuracy_score(
    y_test,
    nb_pred
)

In [10]:
comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Logistic Regression': logistic_pred,
    'Gaussian Naive Bayes': nb_pred
})

In [11]:
comparison.head(10)

   Actual  Logistic Regression  Gaussian Naive Bayes
0       0                    1                     0
1       0                    1                     1
2       1                    1                     1
3       1                    1                     1
4       1                    1                     0
5       1                    1                     1
6       1                    1                     1
7       1                    1                     1
8       1                    1                     1
9       1                    1                     1

In [12]:
logistic_accuracy

0.9620253164556962

In [13]:
nb_accuracy

0.8734177215189873

In [14]:
results = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Gaussian Naive Bayes'
    ],
    'Accuracy': [
        logistic_accuracy,
        nb_accuracy
    ]
})

In [15]:
results

                  Model  Accuracy
0   Logistic Regression  0.962025
1  Gaussian Naive Bayes  0.873418

In [16]:
if logistic_accuracy > nb_accuracy:
    print("Logistic Regression performed better.")
elif nb_accuracy > logistic_accuracy:
    print("Gaussian Naive Bayes performed better.")
else:
    print("Both models have the same accuracy.")

Logistic Regression performed better.