In [ ]:
pip install requests pandas

In [2]:
import requests
import pandas as pd

In [4]:
API_KEY = "088131640787e66585ff68cf0e697134"

In [5]:
url = "https://api.themoviedb.org/3/movie/popular"

In [6]:
params = {
    "api_key": API_KEY,
    "language": "en-US",
    "page": 1
}

In [7]:
response = requests.get(url, params=params)
data = response.json()

In [ ]:
data

In [9]:
movies = []

for movie in data["results"]:
    movies.append({
        "Title": movie["title"],
        "Release_Date": movie["release_date"],
        "Rating": movie["vote_average"],
        "Popularity": movie["popularity"],
        "Original_Language": movie["original_language"],
        "Vote_Count": movie["vote_count"]
    })

In [10]:
df = pd.DataFrame(movies)

In [11]:
df.head()

,Title,Release_Date,Rating,Popularity,Original_Language,Vote_Count
0,Spider-Man: Brand New Day,2026-07-28,8.000,1519.8510,en,301
1,The Odyssey,2026-07-15,7.944,1166.5658,en,1859
2,Supergirl,2026-06-24,6.800,630.4075,en,1139
3,Masters of the Universe,2026-06-03,7.285,486.7027,en,1347
4,Disclosure Day,2026-06-10,7.407,397.2506,en,2040

In [12]:
df.to_csv("tmdb_movies.csv", index=False)

In [14]:
url = "https://api.themoviedb.org/3/movie/top_rated"
response = requests.get(url, params=params, timeout=30)
data = response.json()
top_movies = []
for movie in data["results"]:
    top_movies.append({
        "Title": movie["title"],
        "Release_Date": movie["release_date"],
        "Rating": movie["vote_average"],
        "Popularity": movie["popularity"]
    })
top_df = pd.DataFrame(top_movies)
top_df.to_csv("top_rated_movies.csv", index=False)

In [15]:
top_df.head()

                             Title Release_Date  Rating  Popularity
0  Avatar Aang: The Last Airbender   2026-07-24   9.400    303.9461
1              Accidental Partners   2026-03-12   8.976     28.9079
2                          Swapped   2026-05-01   8.892     70.1201
3         The Shawshank Redemption   1994-09-23   8.726     93.1432
4                          Michael   2026-04-22   8.694    115.7425