In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("student_data.csv")
df.head(5)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [3]:
df['higher'] = df['higher'].map({
    'yes': 1,
    'no': 0
})

In [4]:
df['higher'].value_counts()

higher
1    375
0     20
Name: count, dtype: int64

In [5]:
numerical_features = [
    'age',
    'Medu',
    'Fedu',
    'traveltime',
    'studytime',
    'failures',
    'famrel',
    'freetime',
    'goout',
    'Dalc',
    'Walc',
    'health',
    'absences',
    'G1',
    'G2'
]

In [6]:
X = df[numerical_features]
y = df['higher']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
scaler = StandardScaler()

In [9]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
linear_svm = SVC(kernel='linear')
linear_svm.fit(X_train_scaled, y_train)
linear_pred = linear_svm.predict(X_test_scaled)
linear_accuracy = accuracy_score(
    y_test,
    linear_pred
)

In [11]:
rbf_svm = SVC(kernel='rbf')
rbf_svm.fit(X_train_scaled, y_train)
rbf_pred = rbf_svm.predict(X_test_scaled)
rbf_accuracy = accuracy_score(
    y_test,
    rbf_pred
)

In [12]:
results = pd.DataFrame({
    'Kernel': [
        'Linear',
        'RBF'
    ],
    'Accuracy': [
        linear_accuracy,
        rbf_accuracy
    ]
})

In [13]:
results

   Kernel  Accuracy
0  Linear  0.974684
1     RBF  0.974684

In [15]:
if linear_accuracy > rbf_accuracy:
    print("\nBetter Kernel: Linear")
elif rbf_accuracy > linear_accuracy:
    print("\nBetter Kernel: RBF")
else:
    print("\nBoth kernels have the same accuracy.")

Both kernels have the same accuracy.